language: node_js
node_js:
  - "12.13.0"
os:
  - linux
  - osx
  - windows
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libc6-dev-i386 gcc-multilib g++-multilib        ; fi'
  - "if [[ \"$TRAVIS_OS_NAME\" == \"linux\" && \"$TRAVIS_PULL_REQUEST\" = \"false\" ]]; then curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash; fi"
  - 'if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then npm install -g snyk; fi'

before_script:
  - npm install
  - 'if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then snyk auth $SNYK_TOKEN; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then fossa init && fossa; fi'
  - mkdir prebuild-src
  - 'if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then cp -R src/. prebuild-src/; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then xcopy src prebuild-src //E //C //Q //Y; fi'
  - node prebuild-minify.js
  - cd prebuild-src
  - npm install
  - 'if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then snyk protect; fi'
  - 'if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then snyk test; fi'
  - cd ..

script:
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./node_modules/.bin/electron-builder build -l -p never        ; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./node_modules/.bin/electron-builder build -m -p never          ; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then node_modules\\.bin\\electron-builder build -w -p never      ; fi'

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rBDPbnv7goHiGlcy5fyYZf4Qt/rLUPk9+cz+2uQhTJx9O5rTE3p4BdukXLQoWOsd7XF8wvwOT6PPJTPeznLE/cW6TU7KobTLt5D44QH+ELYtc/vBz5iJd/waMeJXe1GF8Yh2Xqcvq9D5IMjroQMTjzCmP16RhrCrjmsWdmOKSbT+BXVcu1w79ly9ON0TN9IxCXH00YMxmnIvQq7PabEda2JBwys85gVXGFQt625kYQAHUp7ihNCfzrWdjkdsYeEWTu0axlVESAeLMWGoRUsYGVSaAnrXPRdW4OPbU8k0LhjwsAxkKk0VjmhsXvV2m6QKZJbXE99NMYNQksXVdi4mHNtgFDR6hSrJjIr2SLvS4aTfSrTxWPPPR+Kh+4Ocpnep5oH8vPD20dKMiFINzyzzqxlRL3MukUt5oI2ZFHNcnBogaMwSjdf2CDSIO/DI3VZCA+z388hDDUTT1x8UCkokXuXSg9PQCXYX/6fZd565GZhcHbwGEQ5aPGqzZ3/00T7E4B9Ip3UW0tZ8cXm+U+nvgT7KvjD4xby24Cr8YDaoJBK0eT/vbQM7cxl9VKPfkVU8NsYIfV8dmai1ieR1Lnor3iL5xWPsOcjkItahUPjRQLfBEcXNYoLoYEkr7txhLIhMM+q2w5hs2FmbLRLn0qwExYxtTS/rk3NyYZzZgJwtEBc=
  file:
    - "dist/eDEX-UI Linux (i386).AppImage"
    - "dist/eDEX-UI Linux (x86_64).AppImage"
    - "dist/eDEX-UI MacOS Image.dmg"
    - "dist/eDEX-UI Windows Installer.exe"
  options:
    draft: true
  on:
    repo: GitSquared/edex-ui
    branch: master
    tags: true
